### PR TITLE
Chat Message Backend API 

### LINKED ISSUE #46: FEATURE: MVP issues for Chat Backend
# Feature Summary 

The aim is to have a chat box on the user commons page so that admin and users can send messages between each other.

This issue targets the CRUD backend for the basic commons chat feature.

# Discussion

This is a big feature, so it should be broken up into multiple issues; the list below is one suggestion.

Remember "minimum viable product"; the first iteration of this would be a single chat room for each Commons, without DM features; just a global chat where everyone sees everything.   

The list below mentions "hiding" messages (rather than deleting them).  That's not part of MVP, so make sure that all of the MVP features get done first.  However, I do suggest including the `private boolean hidden;` field in the entity even in the first iteration; database changes later are much more disruptive (since we don't have a good database migration strategy yet), so it's better to include all of the fields you might need in the initial run.

To that end, we might also include these fields in the entity:

`private boolean dm;`
`private Long toUserId`

The `dm` field would initially always be false, and the toUserId field would be `null`; we'll use those fields later when/if we implement DMs (but that will be a separate Epic.)

##  CRUD backend for messages MVP

- [x] There is an entity/repository for a ChatMessage.  A ChatMessage should have an id, userId, commonsId and a message payload.   You can use the `@CreationTimestamp` technique to automatically get a timestamp on the message. 
- [x] Include these fields for future use:
       `private boolean hidden;`
       `private Long toUserId`
- [x] The entity/repository for a ChatMessage should also have a "hidden" field that is initially false.  (This is because rather than deleting messages, we want to just "mark them as hidden".   This is to prevent users from using the chat to harass other users by sending inappropriate messages and then deleting them; messages marked as hidden remain in the database (so that they can be retained as evidence) but are not shown.   
- [x] There is a backend POST endpoint `/api/chat/post` where any user can create a message for a particular commonsId, provided they are a member of that commons.  If they have not joined that commons, that should be a 403 error.  The `hidden` field is initially `false`.   The endpoint should take these parameters: `commonsId` and `content`.   The userId should be determined automatically from the currentUser service on the backend, and should not be passed as a parameter. The `dm` field should always be set to `false` right now, and the `toUserId` set to null.
- [x] There is a backend endpoint `/api/chat/get` that takes a commonsId as a param, for retrieving chat messages for a particular commons that operates similar to the backend endpoint for jobs, in that it is paged, and sorted.   The endpoint should retrieve the most recent messages first, and should exclude any "hidden" messages.  It should retrieve messages for a particular commons only if the user is a member of that commons, or the user is an admin, otherwise it should return a 403

### LINKED ISSUE #71: FEAT: Commons chat backend nice to haves
## Specifications
- [x] There is a backend PUT endpoint /api/chat/hide with param id where any user can "hide" any of their own messages; however the message should not be permanently deleted, but rather just "marked as hidden" by setting hidden to true. The endpoint should return 403 if (the message doesn't belong to the user AND the user is not an admin). If the opposite of that is true, i.e. (message belongs to user OR user is an admin), then the message will be marked as hidden. This should also invalidate the React Query cache for /api/chat/get and force a refresh of the chat window.
- [x] There is a backend endpoint /api/chat/admin/hidden (param commonsId) for the Admin only that retrieves all hidden messages for a given commons (paged).
- [x] There is a backend endpoint /api/chat/admin/get (param commonsId) for the Admin that retrieves all messages for a given commons including hidden ones (paged).

### PR DESCRIPTION
**Pull request by dscpsyl**
## Overview

In this PR, we fully implement the chat API backend, complete with user and admin get/post/put as specified in #1. This is an extension of PR #68 and thus has been merged into one. The comments and questions from that PR still stand and should be discussed. Refer to #68 for more details. 

## Tests

- [x] Backend Unit tests (`mvn test`) pass
- [x] Backend Test coverage (`mvn test jacoco:report`) 100%
- [x] Backend Mutation tests (`mvn test pitest:mutationCoverage`) 100% 

## Linked Issues

Closes #46 
Closes #71

### CODE REVIEW

**Review by iain801 — DISMISSED** [review]
Been using it to develop the frontend, been working well!

File: src/main/java/edu/ucsb/cs156/happiercows/controllers/ChatMessageController.java [hunk 1]
```diff
@@ -0,0 +1,167 @@
...
+    private UserCommonsRepository userCommonsRepository;
+
+    @Autowired
+    ObjectMapper mapper;
+
+    @Operation(summary = "Get all chat messages", description = "Get all chat messages associated with a specific commons.")
+    @PreAuthorize("hasAnyRole('ROLE_USER', 'ROLE_ADMIN')")
+    @GetMapping("/get")
+    public ResponseEntity<Object> getChatMessages(@Parameter(description = "The id of the common") @RequestParam Long commonsId,
+                                            @Parameter(name="page") @RequestParam int page,
```
Comment (iain801) [inline src/main/java/edu/ucsb/cs156/happiercows/controllers/ChatMessageController.java:49]: Please make page and size optional, as users will not have the option to use them. This is incompatible with the MVP frontend

**Review by iain801 — CHANGES_REQUESTED** [review]

**Comment by iain801** [comment]
Also, the GET methods always return nothing for the content. I would prefer if the /api/chat/get/all endpoint still existed and only took in the commonsId.

File: src/main/java/edu/ucsb/cs156/happiercows/controllers/ChatMessageController.java (hunk 1 above)
Comment (dscpsyl) [reply src/main/java/edu/ucsb/cs156/happiercows/controllers/ChatMessageController.java:49]: I'll make it so that `page`and `size` are optional parameters that default to `0` and `10`, respectively.

**Comment by dscpsyl** [comment]
@iain801 Unfortunately, the specifications require that all returns are pagable. I modeled it after `jobs` if you want to reference and see how that is implemented. Please make sure that the first page you're requesting is `0`. As of writing this, the qa deployment has my branch if you would like to test out swagger on it. If you're still having issues, let me know!

**Comment by iain801** [comment]
Actually, I will create a new PR tomorrow that will encompass all the backend and frontend MVP, so that the tree and merging is simpler for TA's

**Comment by iain801** [comment]
And the page 0 will have the most recent messages?

**Review by iain801 — DISMISSED** [review]
Thanks for your great work @dscpsyl ! Reopening this and approving it!

File: src/main/java/edu/ucsb/cs156/happiercows/controllers/ChatMessageController.java [hunk 2]
```diff
@@ -0,0 +1,167 @@
...
+                                            @Parameter(name="size") @RequestParam int size) {
+        
+        // Make sure the user is part of the commons or is an admin
+        Authentication auth = SecurityContextHolder.getContext().getAuthentication();
+        if (!auth.getAuthorities().stream().anyMatch(a -> a.getAuthority().equals("ROLE_ADMIN"))){
+            log.info("User is not an admin");
+            User u = getCurrentUser().getUser();
+            Long userId = u.getId();
```
Comment (chriscerie) [inline src/main/java/edu/ucsb/cs156/happiercows/controllers/ChatMessageController.java]:
```suggestion
            User user = getCurrentUser().getUser();
            Long userId = user.getId();
```

File: src/main/java/edu/ucsb/cs156/happiercows/controllers/ChatMessageController.java [hunk 3]
```diff
@@ -0,0 +1,167 @@
...
+    
+    @Operation(summary = "Create a chat message", description = "Create a chat message associated with a specific commons")
+    @PreAuthorize("hasAnyRole('ROLE_USER', 'ROLE_ADMIN')")
+    @PostMapping("/post")
+    public ResponseEntity<Object> createChatMessage(@Parameter(description = "The id of the common") @RequestParam Long commonsId,
+                                                    @Parameter(description = "The message to be sent") @RequestParam String content) {
+        
+        // Get user info
+        User u = getCurrentUser().getUser();
+        Long userId = u.getId();
```
Comment (chriscerie) [inline src/main/java/edu/ucsb/cs156/happiercows/controllers/ChatMessageController.java]:
```suggestion
        User user = getCurrentUser().getUser();
        Long userId = user.getId();
```

File: src/main/java/edu/ucsb/cs156/happiercows/controllers/ChatMessageController.java [hunk 4]
```diff
@@ -0,0 +1,167 @@
...
+        // Try to get the chat message
+        Optional<ChatMessage> chatMessageLookup = chatMessageRepository.findById(chatMessageId);
+        if (!chatMessageLookup.isPresent()) {
+            return ResponseEntity.status(HttpStatus.NOT_FOUND).build();
+        }
+        ChatMessage chatMessage = chatMessageLookup.get();
+
+        // Get user info
+        User u = getCurrentUser().getUser();
+        Long userId = u.getId();
```
Comment (chriscerie) [inline src/main/java/edu/ucsb/cs156/happiercows/controllers/ChatMessageController.java]:
```suggestion
        User user = getCurrentUser().getUser();
        Long userId = user.getId();
```

**Review by chriscerie — CHANGES_REQUESTED** [review]
Let's avoid setting a precedent of creating one letter variables.

**Review by iain801 — APPROVED** [review]
No serious changes since last approval

File: src/main/java/edu/ucsb/cs156/happiercows/controllers/ChatMessageController.java (hunk 1 above)
Comment (pconrad) [reply src/main/java/edu/ucsb/cs156/happiercows/controllers/ChatMessageController.java:49]: Ian... I think for a chat channel, if you don't have paging, that's not MVP.    We learned with the jobs interface, that you have something that grows quickly (which an active chat channel with users would), the stack bogs down really fast if you don't have paging in place.

**Review by pconrad — APPROVED** [review]
A note.. I appreciate removing all of the unused imports. But please, in the future, put that in a separate PR.  It clutters up the diff, and makes it harder to see what's going on.

If I know that the PR is 100% removing unused imports, that's much easier to review.
