### PR TITLE
FIX: Removed 404 Error Page on Navigation and Reload

### LINKED ISSUE #33: BUG: 404 Error Page Shows Whenever Navigating to New Page
### Summary

Whenever a user navigates to a new page on the site, the 404 error page flashes briefly.

This interrupts the flow of the site and can be confusing.

We hope to remove this screen from appearing unless there is an actual 404 error.

### Expected Behavior

Pages should be navigated directly rather than briefly showing 404.

### Current / Observed Behavior

Pages flash 404 Error screen.

### Steps to Reproduce

Look at the logs to see when the job actually ran.

### Implementation Notes

See this for some insight into the issue:
[https://stackoverflow.com/questions/27928372/react-router-urls-dont-work-when-refreshing-or-writing-manually](url)

# To test

Navigate between pages after deploying to Dokku qa as both an admin and regular user. Make sure to visit new/uncached pages to ensure functionality for new users.

### PR DESCRIPTION
**Pull request by iain801**
## Overview

In this PR, we remove the issue of the 404 Error screen appearing briefly whenever a page is loaded or reloaded. We accomplish this by rendering a blank page until the correct one has been served to the client. This also has a secondary benefit of reducing page loading times, as it removes the initial React Router query (Which resulted in 404).

## Screenshots (Optional)

*Insert absence of 404 Error*

## Future Possibilities (Optional)

Some possible points could be:
- Rather than serving a blank page, we could maintain the current page (if applicable) until the new one is ready.
- It could also be nice to refactor the app to use the newer React data routers, which have some nice features for mitigating similar issues

## Validation (Optional)

1. Deploy this branch on dokku (localhost is too fast to replicate the issue).
2. Navigate to a page other than root 
3. Reload the page repeatedly and make sure “404” never appears

## Tests

- [x] Backend Unit tests (`mvn test`) pass
- [x] Backend Test coverage (`mvn test jacoco:report`) 100%
- [x] Backend Mutation tests (`mvn test pitest:mutationCoverage`) 100% 
- [x] Frontend Unit tests (`npm test`) pass
- [x] Frontend Test coverage (`npm run coverage`) 100%
- [x] Frontend Mutation tests (`npx stryker run`) 100% 
- [x] Frontend Linting (`npx eslint --fix src`) 

## Linked Issues

Closes #33

### CODE REVIEW

**Review by MPriston — DISMISSED** [review]
Reviewed changes on the App.js file, the new feature works perfectly, other files changes were minor so no bugs were found, LGTM

**Comment by chriscerie** [comment]
> We accomplish this by rendering a blank page until the correct one has been served to the client.

The changes don't seem to do that. It tries to hide the issue by delaying loading by 200ms in hopes the currentuser query wins the introduced race condition, which will fail on high latency networks. Instead I suggest solving the root of the issue and use react-query's flags (e.g., isLoading) to determine when to fallback to blank page.

**Comment by pconrad** [comment]
> > We accomplish this by rendering a blank page until the correct one has been served to the client.
> 
> The changes don't seem to do that. It tries to hide the issue by delaying loading by 200ms in hopes the currentuser query wins the introduced race condition, which will fail on high latency networks. Instead I suggest solving the root of the issue and use react-query's flags (e.g., isLoading) to determine when to fallback to blank page.

I think I agree with @chriscerie here.   This does "appear" to fix the problem, but only with a hack that is tailored to very specific network conditions.  I think a better solution involves tackling this at the root of the problem, which is to say, at the react-query call, along the lines that @chriscerie suggests.   That may mean that there is no "silver bullet" that solves this across the entire app (though some refactoring in `https://github.com/ucsb-cs156-m23/proj-happycows-m23-10am-4/blob/main/frontend/src/main/utils/currentUser.js` might go a long way towards resolving it.)

It's a great first step though, in terms of investigating and understanding the problem.

**Review by pconrad — CHANGES_REQUESTED** [review]
Overall, I'm inclined to agree with what @chriscerie points out here.  It seems that this might "paper over" the problem rather than really addressing it.

Can you take a second look.. or perhaps we can set this one aside and return to it (i.e. make this a draft PR for now while the team works on other things, and then we can return to the problem with a fresh approach in a new PR?)

**Comment by chriscerie** [comment]
Just a hint, react-query used in the hook already gives you the necessary states for whether a resource is still fetching. If you use that to determine whether to display 404 or blank page it’ll be a fairly straightforward fix.

**Comment by iain801** [comment]
That was something I originally thought, but I tested it on varying latency networks on my dev server with a production build deployment from 0 offset (around 10 ms ping latency) to 10 seconds and never saw the 404 page. I do know the race condition is between the client rendering the page and the currentUser being returned from the backend.

**Comment by iain801** [comment]
idk how I never noticed the initialData flag in useCurrentUser

**Comment by iain801** [comment]
just kidding, didnt work

**Comment by iain801** [comment]
Also, currently we serve the 404 Error when the client doesn't have the correct permissions, however, the HTTP standard has [403 Forbidden](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/403) for this purpose.

**Comment by iain801** [comment]
@phtcon check it out now, thanks @chriscerie for the hint

**Review by dscpsyl — DISMISSED** [review]
Much better. I like it

File: frontend/src/App.js [hunk 1]
```diff
@@ -17,44 +19,53 @@ import PlayPage from "main/pages/PlayPage";
 import NotFoundPage from "main/pages/NotFoundPage";
 
 function App() {
-
   const { data: currentUser } = useCurrentUser();
+  const [isLoading, setIsLoading] = useState(true);
```
Comment (chriscerie) [inline frontend/src/App.js]: Don't derive another state from currentUser. This will cause out of sync state where currentUser data is logged in but isLoading is still true. Just read from the data directly during render.

File: frontend/src/App.js [hunk 2]
```diff
@@ -17,44 +19,53 @@ import PlayPage from "main/pages/PlayPage";
...
+
+  // Delay setting the loading state to false
+  useEffect(() => {
+    setIsLoading(currentUser?.initialData);
+  }, [currentUser]);
+
+  // Define admin routes
```
Comment (chriscerie) [inline frontend/src/App.js]:
```suggestion
```

File: frontend/src/App.js [hunk 3]
```diff
@@ -17,44 +19,53 @@ import PlayPage from "main/pages/PlayPage";
...
+      <Route path="/admin/jobs" element={<AdminJobsPage />} />
+      <Route path="/admin/reports" element={<AdminReportsPage />} />
+      <Route path="/admin/report/:reportId" element={<AdminViewReportPage />} />
+      <Route path="/admin/createcommons" element={<AdminCreateCommonsPage />} />
+      <Route path="/admin/listcommons" element={<AdminListCommonsPage />} />
+      <Route path="/admin/editcommons/:id" element={<AdminEditCommonsPage />} />
+    </>
+  ) : null;
+
+  // Define user routes
```
Comment (chriscerie) [inline frontend/src/App.js]:
```suggestion
```

File: frontend/src/App.js [hunk 4]
```diff
@@ -17,44 +19,53 @@ import PlayPage from "main/pages/PlayPage";
...
+  const userRoutes = hasRole(currentUser, "ROLE_USER") ? (
+    <>
+      <Route path="/profile" element={<ProfilePage />} />
+      <Route path="/leaderboard/:commonsId" element={<LeaderboardPage />}/>
+      <Route path="/play/:commonsId" element={<PlayPage />} />
+    </>
+  ) : null;
+
+  // Choose the homepage based on roles
```
Comment (chriscerie) [inline frontend/src/App.js]:
```suggestion
```

File: frontend/src/App.js [hunk 5]
```diff
@@ -17,44 +19,53 @@ import PlayPage from "main/pages/PlayPage";
...
-             <Route path="/profile" element={<ProfilePage />} />
-             <Route path="/leaderboard/:commonsId" element={<LeaderboardPage />}/>
-             <Route path="/play/:commonsId" element={<PlayPage />} />
-           </>
-          )
-        }
-        <Route path="*" element={<NotFoundPage />} />
-      </Routes>
+      {isLoading ? (
+          <LoadingPage /> // Loading screen
```
Comment (chriscerie) [inline frontend/src/App.js]:
```suggestion
          <LoadingPage />
```

File: frontend/src/App.js [hunk 6]
```diff
@@ -17,44 +19,53 @@ import PlayPage from "main/pages/PlayPage";
...
+        ) : (
+        <Routes>
+          {homeRoute}
+          {adminRoutes}
+          {userRoutes}
+          <Route path="*" element={<NotFoundPage />} /> {/* Fallback 404 route */}
```
Comment (chriscerie) [inline frontend/src/App.js]:
```suggestion
          <Route path="*" element={<NotFoundPage />} />
```

**Review by chriscerie — CHANGES_REQUESTED** [review]
Much better. Few things.

**Comment by iain801** [comment]
@phtcon are deleting all the comments the correct move here?

**Comment by chriscerie** [comment]
You don’t need a comment to tell you a variable called `adminRoutes` defines the admin routes. Favor meaningful comments that tell you why the code is there than what the code does.

**Review by dscpsyl — APPROVED** [review]

**Review by pconrad — APPROVED** [review]
LGTM!  Much better than the previous approach.
